export interface OptionType {
    label: string;
    value: string | number;
  }
  

  export const languages: OptionType[] = [
    { label: "English", value: "English" },
    { label: "Mandarin Chinese", value: "Mandarin Chinese" },
    { label: "Hindi", value: "Hindi" },
    { label: "Spanish", value: "Spanish" },
    { label: "French", value: "French" },
    { label: "Arabic", value: "Arabic" },
    { label: "Bengali", value: "Bengali" },
    { label: "Portuguese", value: "Portuguese" },
    { label: "Russian", value: "Russian" },
    { label: "Urdu", value: "Urdu" },
    { label: "Indonesian", value: "Indonesian" },
    { label: "German", value: "German" },
    { label: "Japanese", value: "Japanese" },
    { label: "Swahili", value: "Swahili" },
    { label: "Marathi", value: "Marathi" },
    { label: "Telugu", value: "Telugu" },
    { label: "Turkish", value: "Turkish" },
    { label: "Tamil", value: "Tamil" },
    { label: "Yue Chinese (Cantonese)", value: "Cantonese" },
    { label: "Vietnamese", value: "Vietnamese" },
    { label: "Tagalog", value: "Tagalog" },
    { label: "Wu Chinese (Shanghainese)", value: "Wu Chinese" },
    { label: "Korean", value: "Korean" },
    { label: "Persian (Farsi)", value: "Persian" },
    { label: "Hausa", value: "Hausa" },
    { label: "Thai", value: "Thai" },
    { label: "Gujarati", value: "Gujarati" },
    { label: "Javanese", value: "Javanese" },
    { label: "Italian", value: "Italian" },
    { label: "Bhojpuri", value: "Bhojpuri" },
    { label: "Hakka Chinese", value: "Hakka Chinese" },
    { label: "Burmese", value: "Burmese" },
    { label: "Polish", value: "Polish" },
    { label: "Ukrainian", value: "Ukrainian" },
    { label: "Kannada", value: "Kannada" },
    { label: "Oromo", value: "Oromo" },
    { label: "Malayalam", value: "Malayalam" },
    { label: "Sundanese", value: "Sundanese" },
    { label: "Amharic", value: "Amharic" },
    { label: "Romanian", value: "Romanian" },
    { label: "Pashto", value: "Pashto" },
    { label: "Igbo", value: "Igbo" },
    { label: "Azerbaijani", value: "Azerbaijani" },
    { label: "Fula", value: "Fula" },
    { label: "Maithili", value: "Maithili" },
    { label: "Serbo-Croatian", value: "Serbo-Croatian" },
    { label: "Hmong", value: "Hmong" },
    { label: "Greek", value: "Greek" },
    { label: "Sinhalese", value: "Sinhalese" },
    { label: "Khmer", value: "Khmer" },
    { label: "Cebuano", value: "Cebuano" },
    { label: "Madurese", value: "Madurese" },
    { label: "Quechua", value: "Quechua" },
    { label: "Swedish", value: "Swedish" },
    { label: "Dutch", value: "Dutch" },
    { label: "Hungarian", value: "Hungarian" },
    { label: "Shona", value: "Shona" },
    { label: "Belarusian", value: "Belarusian" },
    { label: "Zulu", value: "Zulu" },
    { label: "Hebrew", value: "Hebrew" },
    { label: "Czech", value: "Czech" },
    { label: "Kinyarwanda", value: "Kinyarwanda" },
    { label: "Bavarian", value: "Bavarian" },
    { label: "Somali", value: "Somali" },
    { label: "Bulgarian", value: "Bulgarian" },
    { label: "Ilocano", value: "Ilocano" },
    { label: "Xhosa", value: "Xhosa" },
    { label: "Slovak", value: "Slovak" },
    { label: "Lithuanian", value: "Lithuanian" },
    { label: "Albanian", value: "Albanian" },
    { label: "Danish", value: "Danish" },
    { label: "Mongolian", value: "Mongolian" },
    { label: "Tigrinya", value: "Tigrinya" },
    { label: "Bosnian", value: "Bosnian" },
    { label: "Latvian", value: "Latvian" },
    { label: "Estonian", value: "Estonian" },
    { label: "Macedonian", value: "Macedonian" },
    { label: "Bambara", value: "Bambara" },
    { label: "Lao", value: "Lao" },
    { label: "Malagasy", value: "Malagasy" },
    { label: "Wolof", value: "Wolof" },
    { label: "Luxembourgish", value: "Luxembourgish" },
    { label: "Faroese", value: "Faroese" },
    { label: "Icelandic", value: "Icelandic" },
    { label: "Scottish Gaelic", value: "Scottish Gaelic" },
    { label: "Welsh", value: "Welsh" },
    { label: "Irish", value: "Irish" },
    { label: "Corsican", value: "Corsican" },
    { label: "Sicilian", value: "Sicilian" },
    { label: "Tatar", value: "Tatar" },
    { label: "Ossetian", value: "Ossetian" },
    { label: "Chuvash", value: "Chuvash" },
    { label: "Ainu", value: "Ainu" },
    { label: "Basque", value: "Basque" },
    { label: "Galician", value: "Galician" },
    { label: "Breton", value: "Breton" },
    { label: "Sardinian", value: "Sardinian" },
    { label: "Nahuatl", value: "Nahuatl" },
    { label: "Guarani", value: "Guarani" },
    { label: "Mapudungun", value: "Mapudungun" },
    { label: "Hawaiian", value: "Hawaiian" },
    { label: "Samoan", value: "Samoan" },
    { label: "Tahitian", value: "Tahitian" },
    { label: "Fijian", value: "Fijian" },
    { label: "Tongan", value: "Tongan" },
    { label: "Chamorro", value: "Chamorro" },
    { label: "Rapa Nui", value: "Rapa Nui" },
    { label: "Maori", value: "Maori" }
  ];
  
  
  export const educationLevels: OptionType[] = [
    { label: "No Formal Education", value: "No Formal Education" },
    { label: "Primary School", value: "Primary School" },
    { label: "Middle School", value: "Middle School" },
    { label: "High School", value: "High School" },
    { label: "High School Diploma or Equivalent", value: "High School Diploma" },
    { label: "Vocational Training", value: "Vocational Training" },
    { label: "Technical Diploma", value: "Technical Diploma" },
    { label: "Certificate Program", value: "Certificate Program" },
    { label: "Associate Degree", value: "Associate" },
    { label: "Bachelor's Degree", value: "Bachelors" },
    { label: "Postgraduate Diploma", value: "Postgraduate Diploma" },
    { label: "Master's Degree", value: "Masters" },
    { label: "Doctorate (PhD, MD, JD, etc.)", value: "Doctorate" },
    { label: "Postdoctoral Studies", value: "Postdoctoral" },
    { label: "Professional Certification", value: "Professional Certification" },
    { label: "MBA (Master of Business Administration)", value: "MBA" },
    { label: "Medical Degree (MBBS, MD, DO)", value: "Medical Degree" },
    { label: "Law Degree (LLB, JD)", value: "Law Degree" },
    { label: "Engineering Degree", value: "Engineering Degree" },
    { label: "Teaching Certification", value: "Teaching Certification" },
    { label: "Adult Education Program", value: "Adult Education" },
    { label: "Trade School", value: "Trade School" },
    { label: "Others", value: "Others" }
  ];
  
  export const jobRoles: OptionType[] = [
    { label: "Software Engineer", value: "Software Engineer" },
    { label: "Data Scientist", value: "Data Scientist" },
    { label: "Product Manager", value: "Product Manager" },
    { label: "UX Designer", value: "UX Designer" },
    { label: "UI Designer", value: "UI Designer" },
    { label: "Full Stack Developer", value: "Full Stack Developer" },
    { label: "Backend Developer", value: "Backend Developer" },
    { label: "Frontend Developer", value: "Frontend Developer" },
    { label: "DevOps Engineer", value: "DevOps Engineer" },
    { label: "Cloud Engineer", value: "Cloud Engineer" },
    { label: "AI/ML Engineer", value: "AI/ML Engineer" },
    { label: "Cybersecurity Specialist", value: "Cybersecurity Specialist" },
    { label: "Database Administrator", value: "Database Administrator" },
    { label: "Systems Analyst", value: "Systems Analyst" },
    { label: "Business Analyst", value: "Business Analyst" },
    { label: "IT Support Specialist", value: "IT Support Specialist" },
    { label: "Network Engineer", value: "Network Engineer" },
    { label: "Mobile App Developer", value: "Mobile App Developer" },
    { label: "Embedded Systems Engineer", value: "Embedded Systems Engineer" },
    { label: "Game Developer", value: "Game Developer" },
    { label: "Software Architect", value: "Software Architect" },
    { label: "Technical Program Manager", value: "Technical Program Manager" },
    { label: "Quality Assurance Engineer", value: "Quality Assurance Engineer" },
    { label: "Test Automation Engineer", value: "Test Automation Engineer" },
    { label: "Data Engineer", value: "Data Engineer" },
    { label: "Big Data Engineer", value: "Big Data Engineer" },
    { label: "Data Analyst", value: "Data Analyst" },
    { label: "Machine Learning Researcher", value: "Machine Learning Researcher" },
    { label: "Deep Learning Engineer", value: "Deep Learning Engineer" },
    { label: "Computer Vision Engineer", value: "Computer Vision Engineer" },
    { label: "NLP Engineer", value: "NLP Engineer" },
    { label: "Artificial Intelligence Researcher", value: "Artificial Intelligence Researcher" },
    { label: "Security Engineer", value: "Security Engineer" },
    { label: "Ethical Hacker", value: "Ethical Hacker" },
    { label: "Blockchain Developer", value: "Blockchain Developer" },
    { label: "Smart Contract Developer", value: "Smart Contract Developer" },
    { label: "Cloud Solutions Architect", value: "Cloud Solutions Architect" },
    { label: "IT Manager", value: "IT Manager" },
    { label: "Technical Writer", value: "Technical Writer" },
    { label: "Site Reliability Engineer (SRE)", value: "Site Reliability Engineer" },
    { label: "Robotics Engineer", value: "Robotics Engineer" },
    { label: "Firmware Engineer", value: "Firmware Engineer" },
    { label: "Sales Engineer", value: "Sales Engineer" },
    { label: "Marketing Specialist", value: "Marketing Specialist" },
    { label: "SEO Specialist", value: "SEO Specialist" },
    { label: "Social Media Manager", value: "Social Media Manager" },
    { label: "Graphic Designer", value: "Graphic Designer" },
    { label: "Content Strategist", value: "Content Strategist" },
    { label: "Video Editor", value: "Video Editor" },
    { label: "Digital Marketing Manager", value: "Digital Marketing Manager" },
    { label: "Advertising Manager", value: "Advertising Manager" },
    { label: "Public Relations Specialist", value: "Public Relations Specialist" },
    { label: "Copywriter", value: "Copywriter" },
    { label: "HR Manager", value: "HR Manager" },
    { label: "Recruiter", value: "Recruiter" },
    { label: "Finance Analyst", value: "Finance Analyst" },
    { label: "Investment Analyst", value: "Investment Analyst" },
    { label: "Risk Manager", value: "Risk Manager" },
    { label: "Legal Counsel", value: "Legal Counsel" },
    { label: "Supply Chain Manager", value: "Supply Chain Manager" },
    { label: "Operations Manager", value: "Operations Manager" },
    { label: "Project Manager", value: "Project Manager" },
    { label: "Customer Success Manager", value: "Customer Success Manager" },
    { label: "Account Executive", value: "Account Executive" },
    { label: "Sales Representative", value: "Sales Representative" },
    { label: "Customer Support Specialist", value: "Customer Support Specialist" },
    { label: "Event Manager", value: "Event Manager" },
    { label: "Product Owner", value: "Product Owner" },
    { label: "Scrum Master", value: "Scrum Master" },
    { label: "Other", value: "Other" }
  ];
  
  export const interestFields: OptionType[] = [
    { label: "Artificial Intelligence", value: "AI" },
    { label: "Machine Learning", value: "Machine Learning" },
    { label: "Deep Learning", value: "Deep Learning" },
    { label: "Natural Language Processing (NLP)", value: "NLP" },
    { label: "Computer Vision", value: "Computer Vision" },
    { label: "Cybersecurity", value: "Cybersecurity" },
    { label: "Cloud Computing", value: "Cloud Computing" },
    { label: "DevOps", value: "DevOps" },
    { label: "Software Development", value: "Software Development" },
    { label: "Blockchain", value: "Blockchain" },
    { label: "Cryptography", value: "Cryptography" },
    { label: "Data Science", value: "Data Science" },
    { label: "Data Engineering", value: "Data Engineering" },
    { label: "Big Data Analytics", value: "Big Data" },
    { label: "Internet of Things (IoT)", value: "IoT" },
    { label: "Edge Computing", value: "Edge Computing" },
    { label: "Embedded Systems", value: "Embedded Systems" },
    { label: "Product Management", value: "Product Management" },
    { label: "Game Development", value: "Game Development" },
    { label: "Augmented Reality (AR)", value: "AR" },
    { label: "Virtual Reality (VR)", value: "VR" },
    { label: "Human-Computer Interaction (HCI)", value: "HCI" },
    { label: "Software Architecture", value: "Software Architecture" },
    { label: "Quantum Computing", value: "Quantum Computing" },
    { label: "Bioinformatics", value: "Bioinformatics" },
    { label: "Health Tech", value: "Health Tech" },
    { label: "FinTech", value: "FinTech" },
    { label: "EdTech", value: "EdTech" },
    { label: "AgriTech", value: "AgriTech" },
    { label: "Robotics", value: "Robotics" },
    { label: "Autonomous Vehicles", value: "Autonomous Vehicles" },
    { label: "E-commerce", value: "E-commerce" },
    { label: "UI/UX Design", value: "UI/UX Design" },
    { label: "Mobile App Development", value: "Mobile App Development" },
    { label: "Open Source Contributions", value: "Open Source" },
    { label: "Technical Writing", value: "Technical Writing" },
    { label: "Marketing Analytics", value: "Marketing Analytics" },
    { label: "Business Intelligence", value: "Business Intelligence" },
    { label: "Supply Chain Optimization", value: "Supply Chain" },
    { label: "Social Media Analytics", value: "Social Media Analytics" },
    { label: "Ethical AI", value: "Ethical AI" },
    { label: "Sustainable Technology", value: "Sustainable Technology" },
    { label: "Entrepreneurship", value: "Entrepreneurship" },
    { label: "Others", value: "Others" }
  ];
  
  
  export const timezones: OptionType[] = [
    { label: "(UTC-12:00) Baker Island, Howland Island", value: "Pacific/Baker" },
    { label: "(UTC-11:00) American Samoa, Midway Island", value: "Pacific/Pago_Pago" },
    { label: "(UTC-10:00) Hawaii, Tahiti", value: "Pacific/Honolulu" },
    { label: "(UTC-9:30) Marquesas Islands", value: "Pacific/Marquesas" },
    { label: "(UTC-9:00) Alaska", value: "America/Anchorage" },
    { label: "(UTC-8:00) Pacific Time (US & Canada)", value: "America/Los_Angeles" },
    { label: "(UTC-7:00) Mountain Time (US & Canada)", value: "America/Denver" },
    { label: "(UTC-6:00) Central Time (US & Canada)", value: "America/Chicago" },
    { label: "(UTC-5:00) Eastern Time (US & Canada)", value: "America/New_York" },
    { label: "(UTC-4:00) Atlantic Time (Canada), Caracas", value: "America/Halifax" },
    { label: "(UTC-3:30) Newfoundland", value: "America/St_Johns" },
    { label: "(UTC-3:00) Buenos Aires, São Paulo", value: "America/Argentina/Buenos_Aires" },
    { label: "(UTC-2:00) South Georgia & South Sandwich Islands", value: "Atlantic/South_Georgia" },
    { label: "(UTC-1:00) Azores, Cape Verde", value: "Atlantic/Azores" },
    { label: "(UTC+0:00) London, Lisbon, Casablanca", value: "Europe/London" },
    { label: "(UTC+1:00) Central European Time, West Africa", value: "Europe/Berlin" },
    { label: "(UTC+2:00) Eastern European Time, South Africa", value: "Europe/Athens" },
    { label: "(UTC+3:00) Moscow, Nairobi, Istanbul", value: "Europe/Moscow" },
    { label: "(UTC+3:30) Tehran", value: "Asia/Tehran" },
    { label: "(UTC+4:00) Dubai, Samara", value: "Asia/Dubai" },
    { label: "(UTC+4:30) Kabul", value: "Asia/Kabul" },
    { label: "(UTC+5:00) Islamabad, Karachi, Tashkent", value: "Asia/Karachi" },
    { label: "(UTC+5:30) India Standard Time, Sri Lanka", value: "Asia/Kolkata" },
    { label: "(UTC+5:45) Kathmandu", value: "Asia/Kathmandu" },
    { label: "(UTC+6:00) Dhaka, Almaty, Bishkek", value: "Asia/Dhaka" },
    { label: "(UTC+6:30) Yangon (Rangoon)", value: "Asia/Yangon" },
    { label: "(UTC+7:00) Bangkok, Jakarta, Hanoi", value: "Asia/Bangkok" },
    { label: "(UTC+8:00) Beijing, Singapore, Perth", value: "Asia/Shanghai" },
    { label: "(UTC+8:45) Eucla", value: "Australia/Eucla" },
    { label: "(UTC+9:00) Tokyo, Seoul, Pyongyang", value: "Asia/Tokyo" },
    { label: "(UTC+9:30) Adelaide, Darwin", value: "Australia/Adelaide" },
    { label: "(UTC+10:00) Sydney, Vladivostok", value: "Australia/Sydney" },
    { label: "(UTC+10:30) Lord Howe Island", value: "Australia/Lord_Howe" },
    { label: "(UTC+11:00) Solomon Islands, New Caledonia", value: "Pacific/Guadalcanal" },
    { label: "(UTC+12:00) Fiji, Kamchatka, Auckland", value: "Pacific/Auckland" },
    { label: "(UTC+12:45) Chatham Islands", value: "Pacific/Chatham" },
    { label: "(UTC+13:00) Samoa, Tonga", value: "Pacific/Tongatapu" },
    { label: "(UTC+14:00) Line Islands", value: "Pacific/Kiritimati" }
  ];
  
  
  export const certifications: OptionType[] = [
    { label: "AWS Certified Solutions Architect", value: "AWS Certified Solutions Architect" },
    { label: "AWS Certified Developer", value: "AWS Certified Developer" },
    { label: "AWS Certified SysOps Administrator", value: "AWS Certified SysOps Administrator" },
    { label: "Microsoft Certified: Azure Solutions Architect", value: "Microsoft Certified: Azure Solutions Architect" },
    { label: "Microsoft Certified: Azure Administrator", value: "Microsoft Certified: Azure Administrator" },
    { label: "Google Cloud Professional Cloud Architect", value: "Google Cloud Professional Cloud Architect" },
    { label: "Google Cloud Associate Cloud Engineer", value: "Google Cloud Associate Cloud Engineer" },
    { label: "CompTIA Security+", value: "CompTIA Security+" },
    { label: "CompTIA Network+", value: "CompTIA Network+" },
    { label: "Certified Kubernetes Administrator (CKA)", value: "Certified Kubernetes Administrator (CKA)" },
    { label: "Certified Kubernetes Application Developer (CKAD)", value: "Certified Kubernetes Application Developer (CKAD)" },
    { label: "Certified Kubernetes Security Specialist (CKS)", value: "Certified Kubernetes Security Specialist (CKS)" },
    { label: "Certified Ethical Hacker (CEH)", value: "Certified Ethical Hacker (CEH)" },
    { label: "Offensive Security Certified Professional (OSCP)", value: "Offensive Security Certified Professional (OSCP)" },
    { label: "Certified Information Systems Security Professional (CISSP)", value: "Certified Information Systems Security Professional (CISSP)" },
    { label: "Certified Information Systems Auditor (CISA)", value: "Certified Information Systems Auditor (CISA)" },
    { label: "Certified Information Security Manager (CISM)", value: "Certified Information Security Manager (CISM)" },
    { label: "Cisco Certified Network Associate (CCNA)", value: "Cisco Certified Network Associate (CCNA)" },
    { label: "Cisco Certified Network Professional (CCNP)", value: "Cisco Certified Network Professional (CCNP)" },
    { label: "Cisco Certified Internetwork Expert (CCIE)", value: "Cisco Certified Internetwork Expert (CCIE)" },
    { label: "Project Management Professional (PMP)", value: "Project Management Professional (PMP)" },
    { label: "Certified Scrum Master (CSM)", value: "Certified Scrum Master (CSM)" },
    { label: "Scrum Master Certified (SMC)", value: "Scrum Master Certified (SMC)" },
    { label: "AWS Certified Data Analytics", value: "AWS Certified Data Analytics" },
    { label: "AWS Certified Machine Learning", value: "AWS Certified Machine Learning" },
    { label: "Google Cloud Professional Data Engineer", value: "Google Cloud Professional Data Engineer" },
    { label: "Google Cloud Professional Machine Learning Engineer", value: "Google Cloud Professional Machine Learning Engineer" },
    { label: "Microsoft Certified: Azure AI Engineer", value: "Microsoft Certified: Azure AI Engineer" },
    { label: "Microsoft Certified: Azure Data Engineer", value: "Microsoft Certified: Azure Data Engineer" },
    { label: "Microsoft Certified: Power BI Data Analyst", value: "Microsoft Certified: Power BI Data Analyst" },
    { label: "Salesforce Certified Administrator", value: "Salesforce Certified Administrator" },
    { label: "Salesforce Certified Platform Developer", value: "Salesforce Certified Platform Developer" },
    { label: "Oracle Certified Java Programmer", value: "Oracle Certified Java Programmer" },
    { label: "Oracle Database Administrator Certified", value: "Oracle Database Administrator Certified" },
    { label: "TOGAF Certified Enterprise Architect", value: "TOGAF Certified Enterprise Architect" },
    { label: "ITIL Foundation Certification", value: "ITIL Foundation Certification" },
    { label: "Google Associate Android Developer", value: "Google Associate Android Developer" },
    { label: "ISTQB Certified Tester", value: "ISTQB Certified Tester" },
    { label: "Red Hat Certified Engineer (RHCE)", value: "Red Hat Certified Engineer (RHCE)" },
    { label: "Red Hat Certified System Administrator (RHCSA)", value: "Red Hat Certified System Administrator (RHCSA)" },
    { label: "AWS Certified DevOps Engineer", value: "AWS Certified DevOps Engineer" },
    { label: "HashiCorp Certified Terraform Associate", value: "HashiCorp Certified Terraform Associate" },
    { label: "Certified Blockchain Developer", value: "Certified Blockchain Developer" },
    { label: "Certified Cloud Security Professional (CCSP)", value: "Certified Cloud Security Professional (CCSP)" },
    { label: "Adobe Certified Expert", value: "Adobe Certified Expert" },
    { label: "Google Mobile Web Specialist", value: "Google Mobile Web Specialist" },
    { label: "Certified Big Data Professional", value: "Certified Big Data Professional" },
    { label: "Others", value: "Others" },
  ];
  